version: "3"
services:
  db:
    container_name: web-pos-db
    image: mysql
    environment:
      MYSQL_DATABASE: webpos
      MYSQL_ROOT_PASSWORD: 12
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul



